name: mobidziennikowy_sdk
description: Library for retrieving data from the MobiDziennik API
version: 1.0.0
repository: https://github.com/guamencja/mobidziennik-sdk

environment:
  sdk: ^3.4.4

dependencies:
  http: ^1.2.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
